spring:
  application:
    name: sail
  datasource:
    url: jdbc:postgresql://localhost:5432/sail?currentSchema=sail
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
server:
  port: 8090
  servlet:
    context-path: /api
web: http://localhost:8081