CREATE SCHEMA IF NOT EXISTS sail;

GRANT ALL ON SCHEMA sail TO postgres;

GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA sail TO postgres;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA sail TO postgres;
GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA sail TO postgres;

ALTER DEFAULT PRIVILEGES IN SCHEMA sail GRANT ALL PRIVILEGES ON TABLES TO postgres;
ALTER DEFAULT PRIVILEGES IN SCHEMA sail GRANT ALL PRIVILEGES ON SEQUENCES TO postgres;
ALTER DEFAULT PRIVILEGES IN SCHEMA sail GRANT ALL PRIVILEGES ON FUNCTIONS TO postgres;
ALTER DEFAULT PRIVILEGES IN SCHEMA sail GRANT ALL PRIVILEGES ON TYPES TO postgres;